<?php
/**
 * Created by PhpStorm.
 * User: DaRkBaF
 * Date: 25/07/2018
 * Time: 23:17
 */

namespace App\Forms;


class Form extends \Kris\LaravelFormBuilder\Form
{

    protected $resource = '';

    public function buildForm()
    {
        if ($this->getModel() && $this->getModel()->id){
            $method = 'PUT';
            $url = route( $this->resource . '.update', $this->getModel()->id);
        }else {
            $method = 'POST';
            $url = route( $this->resource . '.store' );
        }
        $this->formOptions = [
            'method' => $method,
            'url' => $url
        ];
        parent::buildForm(); // TODO: Change the autogenerated stub
    }

    public function redirectIfNotValid($destination = null)
    {
        $values = $this->getFieldValues();
        foreach ($values as $name => $value) {
            $this->getModel()->$name = $value;
        }
        parent::redirectIfNotValid($destination); // TODO: Change the autogenerated stub
    }
}